### ISSUE TITLE
Magic packet seem not to be transmited

### ISSUE THREAD

**Issue by reverbrick** [kroesche/stellaris_eflash#1]
Hello, 
I was really happy to find the flasher as it seem to fit my current project, but I struggle on first step. The magic packet seem not be sent at all and I don't know why. I checked using wireshark and there's nothing sent. console output below:

> Starting BOOTP/TFTP Server ...
> % Complete:   0%
> Reading file (***.bin) to be downloaded
> ... Allocating buffer for file length 125440
> ... Reading the file
> Setting up network connections
> ... Creating sockete for BOOTP server
> ... Creating sockete for TFTP server
> ... Creating sockete for MAGIG packet transmission
> Sending "Magic" packet to initiate Ethernet Boot Loader
> Starting BOOTP/TFTP Server
> Waiting for packet ...
> ... Resending "Magic" packet.
> Waiting for packet ...
> ... Resending "Magic" packet.
> Waiting for packet ...
> ... Resending "Magic" packet.
> Waiting for packet ...

It loops forever, but when I sent magic packet with another software using QT's sockets it flashed the board properly.
Have you came around such issue? It'd be very helpful.

Regards
Daniel

**Comment by kroesche** [comment]
The "magic" packet looks like a broadcast UDP packet. It will be to destination address 255.255.255.255. If you are using this version of eflash, the port will be 40009.

Here is what I see using wireshark on my mac:

```
16	2.160569000	10.0.0.224	255.255.255.255	UDP	72	Source port: 57182  Destination port: 40009
```

**Comment by reverbrick** [comment]
Hello, thanks for a reply, I think there were issues on my side with FireWall. Thanks anyway.
